import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from legicivica.storage.firestore_store import list_laws

GITHUB_URL = "https://github.com/hajeriwalid/legicivica"
AUTHOR = "Walid Hajeri"

DISCLAIMER_EN = """
**This repository is an open-source research experiment in civic tech**
- **Not Legal Advice:** LegiCivica generates automated, AI-assisted text summaries and normative policy scores. It does **not** provide legal advice, legal consultations, or legal characterization under any domestic jurisdiction.
- **No Judicial Weight:** Output scores measure alignment with open international civic frameworks; they do not assess formal legal validity, enforceability, or constitutionality.
- **AI & API Limitations:** Summaries and reference mappings are generated by Large Language Models and automated API parsing; they may contain errors or hallucinated content. Users must independently verify all information against official publications in the *Journal Officiel*.
- **EU AI Act Notice (Regulation EU 2024/1689):** This software is an automated processing system designed for educational and civic research purposes only.
"""

DISCLAIMER_FR = """
**Ce site est une expérimentation open-source de recherche en civic tech**
- **Absence de conseil juridique :** LegiCivica produit des synthèses textuelles automatisées et des évaluations normatives. Il ne fournit aucun conseil juridique ni aucune consultation légale.
- **Absence de valeur juridique :** Les données et scores produits ne jugent ni de la constitutionnalité, ni de la validité juridique, ni de l'opposabilité des textes (compétence exclusive des juridictions).
- **Limites de l'IA :** Les résumés et résolutions de références sont issus de traitements automatisés et de modèles d'IA. Ils peuvent comporter des inexactitudes et erreurs. Seuls les textes publiés au Journal Officiel font foi.
"""

CUSTOM_CSS = """
<style>
:root {
    --lc-accent: #1F3A5F;
    --lc-accent-soft: #E8EEF4;
    --lc-gold: #B4842A;
    --lc-border: #E1DDD3;
}
@media (prefers-color-scheme: dark) {
    :root {
        --lc-accent: #7FA3C9;
        --lc-accent-soft: #1B2733;
        --lc-gold: #D9A94E;
        --lc-border: #33363D;
    }
}

h1#legicivica-title {
    font-family: Georgia, "Iowan Old Style", "Palatino Linotype", serif;
    font-weight: 700;
    letter-spacing: -0.01em;
    margin-bottom: 0.1rem;
}
.lc-tagline {
    color: var(--lc-accent);
    font-size: 1.02rem;
    margin-bottom: 0.4rem;
}
.lc-header-links {
    text-align: right;
}
.lc-header-links a {
    text-decoration: none;
    font-weight: 600;
    color: var(--lc-accent);
}
.lc-header-links .lc-author {
    font-size: 0.85rem;
    opacity: 0.75;
    margin-top: 0.15rem;
}

.lc-score-badge {
    display: inline-block;
    padding: 0.05rem 0.55rem;
    border-radius: 999px;
    background: var(--lc-accent-soft);
    color: var(--lc-accent);
    font-weight: 600;
    font-size: 0.85rem;
}
.lc-civic-badge {
    display: inline-block;
    padding: 0.05rem 0.55rem;
    border-radius: 999px;
    background: color-mix(in srgb, var(--lc-gold) 18%, transparent);
    color: var(--lc-gold);
    font-weight: 600;
    font-size: 0.85rem;
}

.lc-selected-card {
    border: 1px solid var(--lc-accent);
    border-radius: 10px;
    padding: 1rem 1.25rem;
    background: var(--lc-accent-soft);
    margin-bottom: 1.5rem;
}
.lc-selected-card .lc-selected-label {
    text-transform: uppercase;
    letter-spacing: 0.08em;
    font-size: 0.72rem;
    color: var(--lc-accent);
    font-weight: 700;
}

.lc-methodology-card {
    border: 1px solid var(--lc-border);
    border-radius: 10px;
    padding: 1rem 1.25rem;
    height: 100%;
}
.lc-methodology-card h4 {
    margin-top: 0;
}

hr.lc-divider {
    border: none;
    border-top: 1px solid var(--lc-border);
    margin: 2rem 0 1.25rem 0;
}
.lc-footer-links {
    font-size: 0.9rem;
}
</style>
"""


def records_to_dataframe(records: list[dict]) -> pd.DataFrame:
    """
    Turn Firestore law records into the flat table the dashboard needs.

    Pulled out as a standalone function (rather than inlined in the
    Streamlit script body) specifically so it can be unit-tested without
    a live Firestore connection or a running Streamlit process — feed it
    a list of plain dicts shaped like what save_law() writes, get a
    DataFrame back.
    """
    rows = []
    for r in records:
        transparency = r.get("transparency", {}) or {}
        civic = r.get("civic", {}) or {}
        rows.append({
            "jorf_id": r.get("jorf_id", ""),
            "title": r.get("title", ""),
            "publication_date": r.get("publication_date", ""),
            "transparency_score": transparency.get("overall_score"),
            "civic_index": civic.get("civic_index"),
            "summary": r.get("summary", ""),
        })

    df = pd.DataFrame(rows)
    if not df.empty:
        df["publication_date"] = pd.to_datetime(df["publication_date"], errors="coerce")
        df = df.sort_values("publication_date")
    return df


def _build_score_chart(df: pd.DataFrame) -> go.Figure:
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=df["publication_date"],
        y=df["transparency_score"],
        customdata=df["jorf_id"],
        text=df["title"],
        mode="lines+markers",
        name="Transparency score (0-5)",
        line=dict(color="#1F3A5F", width=2),
        marker=dict(size=8),
        hovertemplate="<b>%{text}</b><br>%{x|%-m/%-d/%Y}<br>Transparency: %{y}/5<extra></extra>",
    ))
    fig.add_trace(go.Scatter(
        x=df["publication_date"],
        y=df["civic_index"],
        customdata=df["jorf_id"],
        text=df["title"],
        mode="lines+markers",
        name="Civic index (-5 to +5)",
        line=dict(color="#B4842A", width=2),
        marker=dict(size=8),
        hovertemplate="<b>%{text}</b><br>%{x|%-m/%-d/%Y}<br>Civic index: %{y:+d}<extra></extra>",
    ))
    fig.update_layout(
        clickmode="event+select",
        margin=dict(l=10, r=10, t=10, b=10),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
        hovermode="closest",
        height=380,
    )
    fig.update_xaxes(tickformat="%-m/%-d")
    return fig


def _selected_jorf_id(event) -> str | None:
    if not event:
        return None
    points = event.get("selection", {}).get("points", [])
    if not points:
        return None
    return points[0].get("customdata")


def _render_header() -> None:
    left, right = st.columns([3, 1])
    with left:
        st.markdown('<h1 id="legicivica-title">LegiCivica</h1>', unsafe_allow_html=True)
        st.markdown(
            '<div class="lc-tagline">French Law Transparency Dashboard — '
            "every law below is resolved, explained, and scored automatically "
            "by an AI agent pipeline.</div>",
            unsafe_allow_html=True,
        )
    with right:
        st.markdown(
            f'<div class="lc-header-links">'
            f'<a href="{GITHUB_URL}" target="_blank">↗ Source on GitHub</a>'
            f'<div class="lc-author">Built by {AUTHOR}</div>'
            f"</div>",
            unsafe_allow_html=True,
        )


def _render_methodology() -> None:
    with st.expander("How the scores are calculated", expanded=False):
        col1, col2 = st.columns(2)
        with col1:
            st.markdown(
                """
<div class="lc-methodology-card">
<h4>Transparency score <span class="lc-score-badge">0 – 5</span></h4>
Average of three components, each scored 1–5:

- **Delegation ratio** — how much of what's explained in the law is
  self-executing today versus waiting on an implementing decree that
  doesn't exist yet. Fully self-executing scores 5; mostly delegated
  scores 1.
- **Cross-document complexity** — how many distinct legal codes the law
  touches, and how much of the reference chain could actually be
  resolved. Touching one code with a fully resolved chain scores 5;
  touching many, or leaving references unresolved, scores lower.
- **Concreteness of definitions** — an AI judgment of whether the law's
  key terms are defined concretely or left vague.
</div>
                """,
                unsafe_allow_html=True,
            )
        with col2:
            st.markdown(
                """
<div class="lc-methodology-card">
<h4>Civic index <span class="lc-civic-badge">-5 to +5</span></h4>
Sum of five criteria, each scored -1 (weakens), 0 (neutral / not
applicable), or +1 (reinforces):

- **Legal certainty & prospectivity**
- **Proportionality of obligations**
- **Sunset & review mechanisms**
- **Subsidiarity / local autonomy**
- **Open government & disclosure**

This is a normative judgment against open rule-of-law frameworks — not a
determination of legal or constitutional validity, and not an evaluation
of any individual official.
</div>
                """,
                unsafe_allow_html=True,
            )


def _render_selected_card(record: dict) -> None:
    transparency = record.get("transparency", {}) or {}
    civic = record.get("civic", {}) or {}
    title = record.get("title", record.get("jorf_id", "Untitled"))
    st.markdown(
        f"""
<div class="lc-selected-card">
<div class="lc-selected-label">Selected from chart</div>
<b>{record.get('publication_date', '?')} — {title}</b><br>
<span class="lc-score-badge">Transparency {transparency.get('overall_score')}/5</span>
&nbsp;
<span class="lc-civic-badge">Civic index {civic.get('civic_index'):+d}</span>
</div>
        """,
        unsafe_allow_html=True,
    )


def _render_law_card(record: dict, expanded: bool, highlighted: bool) -> None:
    title = record.get("title", record.get("jorf_id", "Untitled"))
    label = f"{record.get('publication_date', '?')} — {title}"
    if highlighted:
        label = "📍 " + label
    with st.expander(label, expanded=expanded):
        st.write(record.get("summary", ""))

        transparency = record.get("transparency", {}) or {}
        st.markdown(
            f"**Transparency score:** "
            f"<span class='lc-score-badge'>{transparency.get('overall_score')}/{transparency.get('overall_max', 5)}</span>",
            unsafe_allow_html=True,
        )
        for c in transparency.get("components", []):
            st.markdown(f"- [{c.get('score')}/5] **{c.get('label')}** — {c.get('reason')}")

        civic = record.get("civic", {}) or {}
        st.markdown(
            f"**Civic index:** "
            f"<span class='lc-civic-badge'>{civic.get('civic_index'):+d}</span> "
            f"(range {civic.get('civic_index_range')})",
            unsafe_allow_html=True,
        )
        for c in civic.get("criteria", []):
            st.markdown(f"- [{c.get('score'):+d}] **{c.get('label')}** — {c.get('reason')}")
        if civic.get("notice"):
            st.caption(civic["notice"])

        parties = record.get("affected_parties", [])
        if parties:
            st.markdown("**Who's affected:**")
            for p in parties:
                date_part = f" (effective {p.get('effective_date')})" if p.get("effective_date") else ""
                st.markdown(f"- **{p.get('category')}**: {p.get('obligation')}{date_part}")


def _render_footer() -> None:
    st.markdown('<hr class="lc-divider">', unsafe_allow_html=True)
    st.markdown(
        f'<div class="lc-footer-links">'
        f'⚖️ <a href="{GITHUB_URL}" target="_blank">LegiCivica on GitHub</a> · '
        f"built by {AUTHOR}"
        f"</div>",
        unsafe_allow_html=True,
    )
    with st.expander("⚠️ Disclaimer & Legal Notice / Avertissement légal"):
        tab_en, tab_fr = st.tabs(["English", "Français"])
        with tab_en:
            st.markdown(DISCLAIMER_EN)
        with tab_fr:
            st.markdown(DISCLAIMER_FR)


def render() -> None:
    st.set_page_config(page_title="LegiCivica", page_icon="⚖️", layout="wide")
    st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

    _render_header()

    try:
        records = _load_records()
    except Exception as exc:
        st.error(f"Could not load data from Firestore: {exc}")
        st.caption("Check GCP_PROJECT_ID and that you're authenticated (gcloud auth application-default login).")
        return

    if not records:
        st.info("No laws processed yet. The daily poller and historical backfill populate this dashboard.")
        _render_footer()
        return

    df = records_to_dataframe(records)
    by_jorf_id = {r.get("jorf_id"): r for r in records}

    _render_methodology()

    st.subheader("Score evolution over time")
    st.caption("Click a point to highlight that law below.")
    fig = _build_score_chart(df)
    event = st.plotly_chart(fig, key="score_chart", on_select="rerun", selection_mode=["points"])

    selected_id = _selected_jorf_id(event)
    if selected_id and selected_id in by_jorf_id:
        _render_selected_card(by_jorf_id[selected_id])

    st.subheader("Law detail")
    for record in sorted(records, key=lambda r: r.get("publication_date", ""), reverse=True):
        jorf_id = record.get("jorf_id")
        highlighted = jorf_id == selected_id
        _render_law_card(record, expanded=highlighted, highlighted=highlighted)

    _render_footer()


@st.cache_data(ttl=60)
def _load_records() -> list[dict]:
    return list_laws()


if __name__ == "__main__":
    render()
